<a href="https://colab.research.google.com/github/Sathish-Tagore/udacity_tensorflow/blob/main/data_manipulation.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import tensorflow as tf

## Data manipulation

A tensor is a multidimensional array. If the no of axis is one it represents a vector, if the no of axes is 2 it represents a matrix, if axes > 2 then it represents the Kth order tensor

In [ ]:
x = tf.range(12, dtype=tf.float32)
x

<tf.Tensor: shape=(12,), dtype=float32, numpy=
array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11.],
      dtype=float32)>

In [ ]:
x.shape

TensorShape([12])

In [ ]:
tf.size(x)

<tf.Tensor: shape=(), dtype=int32, numpy=12>

In [ ]:
X = tf.reshape(x, (3, 4))
X

<tf.Tensor: shape=(3, 4), dtype=float32, numpy=
array([[ 0.,  1.,  2.,  3.],
       [ 4.,  5.,  6.,  7.],
       [ 8.,  9., 10., 11.]], dtype=float32)>

In [ ]:
tf.zeros((2, 3, 4))

<tf.Tensor: shape=(2, 3, 4), dtype=float32, numpy=
array([[[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]], dtype=float32)>

In [ ]:
tf.ones((2, 3, 4))

<tf.Tensor: shape=(2, 3, 4), dtype=float32, numpy=
array([[[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]]], dtype=float32)>

The following snippet creates a tensor with shape (3, 4). Each of its elements is randomly sampled from a standard Gaussian (normal) distribution with a mean of 0 and a standard deviation of 1

In [ ]:
tf.random.normal(shape=[3, 4])

<tf.Tensor: shape=(3, 4), dtype=float32, numpy=
array([[-0.15671773, -0.5847039 , -0.0674569 , -0.19462246],
       [-2.2324095 ,  2.1703653 ,  0.4312646 ,  1.5430381 ],
       [ 1.3189521 ,  0.8722644 ,  0.19571975, -0.3183358 ]],
      dtype=float32)>

In [ ]:
tf.constant([[2, 1, 4, 3], [1, 2, 3, 4], [4, 3, 2, 1]])

<tf.Tensor: shape=(3, 4), dtype=int32, numpy=
array([[2, 1, 4, 3],
       [1, 2, 3, 4],
       [4, 3, 2, 1]], dtype=int32)>

## Operations

Arithmetic and mathematical functions

In [ ]:
x = tf.constant([3,7,8,9],dtype=tf.float32)
y = tf.constant([1,2,3,4],dtype=tf.float32)

x + y, x - y, x * y, x / y, x ** y  # The ** operator is exponentiation

(<tf.Tensor: shape=(4,), dtype=float32, numpy=array([ 4.,  9., 11., 13.], dtype=float32)>,
 <tf.Tensor: shape=(4,), dtype=float32, numpy=array([2., 5., 5., 5.], dtype=float32)>,
 <tf.Tensor: shape=(4,), dtype=float32, numpy=array([ 3., 14., 24., 36.], dtype=float32)>,
 <tf.Tensor: shape=(4,), dtype=float32, numpy=array([3.       , 3.5      , 2.6666667, 2.25     ], dtype=float32)>,
 <tf.Tensor: shape=(4,), dtype=float32, numpy=
 array([3.0000000e+00, 4.8999996e+01, 5.1200000e+02, 6.5610005e+03],
       dtype=float32)>)

In [ ]:
tf.exp(x)

<tf.Tensor: shape=(4,), dtype=float32, numpy=array([  20.085537, 1096.6332  , 2980.958   , 8103.084   ], dtype=float32)>

We can also concatenate multiple tensors together, stacking them end-to-end to form a larger tensor. We just need to provide a list of tensors and tell the system along which axis to concatenate.

In [ ]:
X = tf.reshape(tf.range(12, dtype=tf.float32), (3, 4))
Y = tf.constant([[2, 1, 4, 3], [1, 2, 3, 4], [4, 3, 2, 1]], dtype=tf.float32)

In [ ]:
X

<tf.Tensor: shape=(3, 4), dtype=float32, numpy=
array([[ 0.,  1.,  2.,  3.],
       [ 4.,  5.,  6.,  7.],
       [ 8.,  9., 10., 11.]], dtype=float32)>

In [ ]:
Y

<tf.Tensor: shape=(3, 4), dtype=float32, numpy=
array([[2., 1., 4., 3.],
       [1., 2., 3., 4.],
       [4., 3., 2., 1.]], dtype=float32)>

In [ ]:
tf.concat([X,Y],axis=0)

<tf.Tensor: shape=(6, 4), dtype=float32, numpy=
array([[ 0.,  1.,  2.,  3.],
       [ 4.,  5.,  6.,  7.],
       [ 8.,  9., 10., 11.],
       [ 2.,  1.,  4.,  3.],
       [ 1.,  2.,  3.,  4.],
       [ 4.,  3.,  2.,  1.]], dtype=float32)>

In [ ]:
tf.concat([X,Y],axis=1)

<tf.Tensor: shape=(3, 8), dtype=float32, numpy=
array([[ 0.,  1.,  2.,  3.,  2.,  1.,  4.,  3.],
       [ 4.,  5.,  6.,  7.,  1.,  2.,  3.,  4.],
       [ 8.,  9., 10., 11.,  4.,  3.,  2.,  1.]], dtype=float32)>

In [ ]:
X == Y

<tf.Tensor: shape=(3, 4), dtype=bool, numpy=
array([[False,  True, False,  True],
       [False, False, False, False],
       [False, False, False, False]])>

In [ ]:
tf.reduce_sum(X)

<tf.Tensor: shape=(), dtype=float32, numpy=66.0>

In [ ]:
tf.reduce_max(X)

<tf.Tensor: shape=(), dtype=float32, numpy=11.0>

In [ ]:
tf.reduce_min(Y)

<tf.Tensor: shape=(), dtype=float32, numpy=1.0>

In [ ]:
tf.reduce_mean(X)

<tf.Tensor: shape=(), dtype=float32, numpy=5.5>

In [ ]:
tf.reduce_prod(Y)

<tf.Tensor: shape=(), dtype=float32, numpy=13824.0>

## Broadcasting


Under certain conditions, even when shapes differ, we can still perform elementwise operations by invoking the broadcasting mechanism. This mechanism works in the following way: First, expand one or both arrays by copying elements appropriately so that after this transformation, the two tensors have the same shape. Second, carry out the elementwise operations on the resulting arrays.

In [ ]:
a = tf.reshape(tf.range(3), (3, 1))
b = tf.reshape(tf.range(2), (1, 2))
a, b

(<tf.Tensor: shape=(3, 1), dtype=int32, numpy=
 array([[0],
        [1],
        [2]], dtype=int32)>,
 <tf.Tensor: shape=(1, 2), dtype=int32, numpy=array([[0, 1]], dtype=int32)>)

0 + 0, 0 + 1 <br>
1 + 0, 1 + 1 <br>
2 + 0, 2 + 1 <br>

In [ ]:
a + b

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[0, 1],
       [1, 2],
       [2, 3]], dtype=int32)>

0 * 0, 0 * 1 <br>
1 * 0, 1 * 1 <br>
2 * 0, 2 * 1 <br>

In [ ]:
a * b

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[0, 0],
       [0, 1],
       [0, 2]], dtype=int32)>

In [ ]:
a * 4

<tf.Tensor: shape=(3, 1), dtype=int32, numpy=
array([[0],
       [4],
       [8]], dtype=int32)>

## Indexing and slicing

In [ ]:
X

<tf.Tensor: shape=(3, 4), dtype=float32, numpy=
array([[ 0.,  1.,  2.,  3.],
       [ 4.,  5.,  6.,  7.],
       [ 8.,  9., 10., 11.]], dtype=float32)>

In [ ]:
X[-1]

<tf.Tensor: shape=(4,), dtype=float32, numpy=array([ 8.,  9., 10., 11.], dtype=float32)>

In [ ]:
X[1:3, 1:]

<tf.Tensor: shape=(2, 3), dtype=float32, numpy=
array([[ 5.,  6.,  7.],
       [ 9., 10., 11.]], dtype=float32)>

In [ ]:
X[2,1]

<tf.Tensor: shape=(), dtype=float32, numpy=9.0>

In [ ]:
Z = tf.reshape(tf.range(12),(3,2,2))
Z

<tf.Tensor: shape=(3, 2, 2), dtype=int32, numpy=
array([[[ 0,  1],
        [ 2,  3]],

       [[ 4,  5],
        [ 6,  7]],

       [[ 8,  9],
        [10, 11]]], dtype=int32)>

In [ ]:
Z[0,0:,0]

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([0, 2], dtype=int32)>

Tensors in TensorFlow are immutable, and cannot be assigned to. Variables in TensorFlow are mutable containers of state that support assignments. Keep in mind that gradients in TensorFlow do not flow backwards through Variable assignments.

In [ ]:
Z[0,0,0] = 7

TypeError: ignored

In [ ]:
X_var = tf.Variable(X)
X_var[1, 2].assign(9)
X_var

<tf.Variable 'Variable:0' shape=(3, 4) dtype=float32, numpy=
array([[ 0.,  1.,  2.,  3.],
       [ 4.,  5.,  9.,  7.],
       [ 8.,  9., 10., 11.]], dtype=float32)>

In [ ]:
X_var = tf.Variable(X)
X_var[0:2, :].assign(tf.ones(X_var[0:2,:].shape, dtype = tf.float32) * 12)
X_var

<tf.Variable 'Variable:0' shape=(3, 4) dtype=float32, numpy=
array([[12., 12., 12., 12.],
       [12., 12., 12., 12.],
       [ 8.,  9., 10., 11.]], dtype=float32)>

## Memory allocation

In [ ]:
before = id(Y)
print(before)
Y = Y + X
print(id(Y))
id(Y) == before

139850847733904
139850847774864


False

In [ ]:
Z = tf.Variable(tf.zeros_like(Y))
print('id(Z):', id(Z))
Z.assign(X + Y)
print('id(Z):', id(Z))

id(Z): 139850847259024
id(Z): 139850847259024


TensorFlow provides the @tf.function decorator to wrap computation inside of a TensorFlow graph that gets compiled and optimized before running. This allows TensorFlow to prune unused values, and to re-use prior allocations that are no longer needed. This minimizes the memory overhead of TensorFlow computations.

In [ ]:
@tf.function
def computations(X,Y):
  Z = tf.zeros_like(Y)
  A = X + Y
  B = A + Y
  C = B + Y
  return C + Y

computations(X,Y)

<tf.Tensor: shape=(3, 4), dtype=float32, numpy=
array([[  8.,  13.,  34.,  39.],
       [ 40.,  53.,  66.,  79.],
       [ 88.,  93.,  98., 103.]], dtype=float32)>

In [ ]:
A = X.numpy()
B = tf.constant(A)
type(A), type(B)

(numpy.ndarray, tensorflow.python.framework.ops.EagerTensor)

In [ ]:
a = tf.constant([3.5]).numpy()
a, a.item(), float(a), int(a)

(array([3.5], dtype=float32), 3.5, 3.5, 3)