<a href="https://colab.research.google.com/github/Sathish-Tagore/udacity_tensorflow/blob/main/linear_algebra.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import tensorflow as tf
import numpy as np
import pandas as pd

### Scalar
A scalar is represented by a tensor with just one element.

In [1]:

x = tf.constant(3.0)
y = tf.constant(2.0)

x + y, x * y, x / y, x**y

(<tf.Tensor: shape=(), dtype=float32, numpy=5.0>,
 <tf.Tensor: shape=(), dtype=float32, numpy=6.0>,
 <tf.Tensor: shape=(), dtype=float32, numpy=1.5>,
 <tf.Tensor: shape=(), dtype=float32, numpy=9.0>)

### Vector
vector is simply a list of scalar values. vectors are represented as one dimensional tensors

In [3]:
x = tf.range(4)
x

<tf.Tensor: shape=(4,), dtype=int32, numpy=array([0, 1, 2, 3], dtype=int32)>

In [4]:
x[3]

<tf.Tensor: shape=(), dtype=int32, numpy=3>

### Length, Dimensionality, and Shape
A vector is just an array of numbers. And just as every array has a length, so does every vector. The length of a vector is commonly called the dimension of the vector.

In [5]:
len(x)

4

When a tensor represents a vector (with precisely one axis), we can also access its length via the .shape attribute. The shape is a tuple that lists the length (dimensionality) along each axis of the tensor. For tensors with just one axis, the shape has just one element.

In [6]:
x.shape

TensorShape([4])

### Matrices
A matrix  consists of  m rows  and  n columns of real-valued scalars. when a matrix has the same number of rows and columns it is called a square matrix.


In [7]:
A = tf.reshape(tf.range(20), (5, 4))
A

<tf.Tensor: shape=(5, 4), dtype=int32, numpy=
array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]], dtype=int32)>

In [16]:
tf.reshape(tf.ones(9), (3,3))

<tf.Tensor: shape=(3, 3), dtype=float32, numpy=
array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]], dtype=float32)>

When we exchange a matrix’s rows and columns, the result is called the transpose of the matrix $A^T$

In [17]:
tf.transpose(A)

<tf.Tensor: shape=(4, 5), dtype=int32, numpy=
array([[ 0,  4,  8, 12, 16],
       [ 1,  5,  9, 13, 17],
       [ 2,  6, 10, 14, 18],
       [ 3,  7, 11, 15, 19]], dtype=int32)>

A special type of the square matrix, a symmetric matrix A is equal to its transpose $A^T$. 

In [18]:
B = tf.constant([[1, 2, 3], [2, 0, 4], [3, 4, 5]])
B

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[1, 2, 3],
       [2, 0, 4],
       [3, 4, 5]], dtype=int32)>

In [19]:
B == tf.transpose(B)

<tf.Tensor: shape=(3, 3), dtype=bool, numpy=
array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])>

### Tensors

Tensors give us a generic way of describing n-dimensional arrays with an arbitrary number of axes. Vectors, for example, are first-order tensors, and matrices are second-order tensors.


In [20]:
X = tf.reshape(tf.range(24), (2, 3, 4))
X

<tf.Tensor: shape=(2, 3, 4), dtype=int32, numpy=
array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]], dtype=int32)>

In [21]:
tf.transpose(X)

<tf.Tensor: shape=(4, 3, 2), dtype=int32, numpy=
array([[[ 0, 12],
        [ 4, 16],
        [ 8, 20]],

       [[ 1, 13],
        [ 5, 17],
        [ 9, 21]],

       [[ 2, 14],
        [ 6, 18],
        [10, 22]],

       [[ 3, 15],
        [ 7, 19],
        [11, 23]]], dtype=int32)>

### Arithmetic operations with tensors

In [22]:
A = tf.reshape(tf.range(20, dtype=tf.float32), (5,4) )
B = A
A, A + B

(<tf.Tensor: shape=(5, 4), dtype=float32, numpy=
 array([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.],
        [12., 13., 14., 15.],
        [16., 17., 18., 19.]], dtype=float32)>,
 <tf.Tensor: shape=(5, 4), dtype=float32, numpy=
 array([[ 0.,  2.,  4.,  6.],
        [ 8., 10., 12., 14.],
        [16., 18., 20., 22.],
        [24., 26., 28., 30.],
        [32., 34., 36., 38.]], dtype=float32)>)

In [23]:
A * B

<tf.Tensor: shape=(5, 4), dtype=float32, numpy=
array([[  0.,   1.,   4.,   9.],
       [ 16.,  25.,  36.,  49.],
       [ 64.,  81., 100., 121.],
       [144., 169., 196., 225.],
       [256., 289., 324., 361.]], dtype=float32)>

Multiplying or adding a tensor by a scalar also does not change the shape of the tensor, where each element of the operand tensor will be added or multiplied by the scalar.

In [24]:
a = 2
X = tf.reshape(tf.range(24), (2,4,3))
(a * X).shape, a + X 

(TensorShape([2, 4, 3]), <tf.Tensor: shape=(2, 4, 3), dtype=int32, numpy=
 array([[[ 2,  3,  4],
         [ 5,  6,  7],
         [ 8,  9, 10],
         [11, 12, 13]],
 
        [[14, 15, 16],
         [17, 18, 19],
         [20, 21, 22],
         [23, 24, 25]]], dtype=int32)>)

### Reduction



In [25]:
x = tf.range(4, dtype=tf.float32)
x, tf.reduce_sum(x)

(<tf.Tensor: shape=(4,), dtype=float32, numpy=array([0., 1., 2., 3.], dtype=float32)>,
 <tf.Tensor: shape=(), dtype=float32, numpy=6.0>)

In [26]:
A, A.shape, tf.reduce_sum(A)

(<tf.Tensor: shape=(5, 4), dtype=float32, numpy=
 array([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.],
        [12., 13., 14., 15.],
        [16., 17., 18., 19.]], dtype=float32)>,
 TensorShape([5, 4]),
 <tf.Tensor: shape=(), dtype=float32, numpy=190.0>)

To reduce the row dimension (axis 0) by summing up elements of all the rows, specify axis=0 

In [27]:
#adds column wise
A_sum_axis0 = tf.reduce_sum(A, axis=0)

A, A_sum_axis0, A_sum_axis0.shape

(<tf.Tensor: shape=(5, 4), dtype=float32, numpy=
 array([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.],
        [12., 13., 14., 15.],
        [16., 17., 18., 19.]], dtype=float32)>,
 <tf.Tensor: shape=(4,), dtype=float32, numpy=array([40., 45., 50., 55.], dtype=float32)>,
 TensorShape([4]))

In [29]:
#adds row wise
A_sum_axis1 = tf.reduce_sum(A, axis=1)

A, A_sum_axis1, A_sum_axis1.shape

(<tf.Tensor: shape=(5, 4), dtype=float32, numpy=
 array([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.],
        [12., 13., 14., 15.],
        [16., 17., 18., 19.]], dtype=float32)>,
 <tf.Tensor: shape=(5,), dtype=float32, numpy=array([ 6., 22., 38., 54., 70.], dtype=float32)>,
 TensorShape([5]))

In [30]:
tf.reduce_sum(A, axis=[0, 1])  # Same as `tf.reduce_sum(A)`

<tf.Tensor: shape=(), dtype=float32, numpy=190.0>

In [31]:
tf.reduce_mean(A), tf.reduce_sum(A) / tf.size(A).numpy()

(<tf.Tensor: shape=(), dtype=float32, numpy=9.5>,
 <tf.Tensor: shape=(), dtype=float32, numpy=9.5>)

In [34]:
tf.reduce_mean(A, axis=0), tf.reduce_sum(A, axis=0) / A.shape[0]


(<tf.Tensor: shape=(4,), dtype=float32, numpy=array([ 8.,  9., 10., 11.], dtype=float32)>,
 <tf.Tensor: shape=(4,), dtype=float32, numpy=array([ 8.,  9., 10., 11.], dtype=float32)>)

In [35]:
tf.reduce_mean(A, axis=1), tf.reduce_sum(A, axis=1) / A.shape[1]

(<tf.Tensor: shape=(5,), dtype=float32, numpy=array([ 1.5,  5.5,  9.5, 13.5, 17.5], dtype=float32)>,
 <tf.Tensor: shape=(5,), dtype=float32, numpy=array([ 1.5,  5.5,  9.5, 13.5, 17.5], dtype=float32)>)

To keep the number of axes unchanged when invoking the function for calculating the sum or mean.

In [37]:
A

<tf.Tensor: shape=(5, 4), dtype=float32, numpy=
array([[ 0.,  1.,  2.,  3.],
       [ 4.,  5.,  6.,  7.],
       [ 8.,  9., 10., 11.],
       [12., 13., 14., 15.],
       [16., 17., 18., 19.]], dtype=float32)>

In [40]:
sum_A = tf.reduce_sum(A, axis=1, keepdims=True)
sum_A

<tf.Tensor: shape=(5, 1), dtype=float32, numpy=
array([[ 6.],
       [22.],
       [38.],
       [54.],
       [70.]], dtype=float32)>

In [41]:
A / sum_A


<tf.Tensor: shape=(5, 4), dtype=float32, numpy=
array([[0.        , 0.16666667, 0.33333334, 0.5       ],
       [0.18181819, 0.22727273, 0.27272728, 0.3181818 ],
       [0.21052632, 0.23684211, 0.2631579 , 0.28947368],
       [0.22222222, 0.24074075, 0.25925925, 0.2777778 ],
       [0.22857143, 0.24285714, 0.25714287, 0.27142859]], dtype=float32)>

In [38]:
sum_A = tf.reduce_sum(A, axis=0, keepdims=True)
sum_A

<tf.Tensor: shape=(1, 4), dtype=float32, numpy=array([[40., 45., 50., 55.]], dtype=float32)>

In [39]:
A / sum_A

<tf.Tensor: shape=(5, 4), dtype=float32, numpy=
array([[0.        , 0.02222222, 0.04      , 0.05454545],
       [0.1       , 0.11111111, 0.12      , 0.12727273],
       [0.2       , 0.2       , 0.2       , 0.2       ],
       [0.3       , 0.2888889 , 0.28      , 0.27272728],
       [0.4       , 0.37777779, 0.36      , 0.34545454]], dtype=float32)>

To calculate the cumulative sum of elements of A along axis=0 (row by row), call the cumsum function

In [42]:
tf.cumsum(A, axis=0)

<tf.Tensor: shape=(5, 4), dtype=float32, numpy=
array([[ 0.,  1.,  2.,  3.],
       [ 4.,  6.,  8., 10.],
       [12., 15., 18., 21.],
       [24., 28., 32., 36.],
       [40., 45., 50., 55.]], dtype=float32)>

### Dot product

In [44]:
y = tf.ones(4, dtype=tf.float32) * 3
x, y, tf.tensordot(x, y, axes=1)

(<tf.Tensor: shape=(4,), dtype=float32, numpy=array([0., 1., 2., 3.], dtype=float32)>,
 <tf.Tensor: shape=(4,), dtype=float32, numpy=array([3., 3., 3., 3.], dtype=float32)>,
 <tf.Tensor: shape=(), dtype=float32, numpy=18.0>)

In [45]:
tf.reduce_sum(x * y)

<tf.Tensor: shape=(), dtype=float32, numpy=18.0>

In [46]:
A.shape

TensorShape([5, 4])

In [47]:
x.shape

TensorShape([4])

In [48]:
tf.linalg.matvec(A,x)

<tf.Tensor: shape=(5,), dtype=float32, numpy=array([ 14.,  38.,  62.,  86., 110.], dtype=float32)>

In [54]:
B = tf.ones((4, 3), tf.float32) * 2
B

<tf.Tensor: shape=(4, 3), dtype=float32, numpy=
array([[2., 2., 2.],
       [2., 2., 2.],
       [2., 2., 2.],
       [2., 2., 2.]], dtype=float32)>

In [55]:
tf.matmul(A,B)

<tf.Tensor: shape=(5, 3), dtype=float32, numpy=
array([[ 12.,  12.,  12.],
       [ 44.,  44.,  44.],
       [ 76.,  76.,  76.],
       [108., 108., 108.],
       [140., 140., 140.]], dtype=float32)>

In [56]:
tf.matmul(B,A)

InvalidArgumentError: ignored

### Norm

A vector norm is a function that maps a vector to a scalar. The Euclidean distance is a $L_2 norm $

1) $$f(αx) = |α|f(x)$$
2) $$f(x + y) \leq f(x) + f(y)$$
3) $$f(x) \geq 0 $$
4) $$ ∀i , [x]_i = 0 \Leftrightarrow f(x) = 0 $$

$$ ||x||_2 = \sqrt{\sum_{i=1}^n x_i^2}$$



In [58]:
u = tf.constant([3,4], dtype=tf.float32)
tf.norm(u)

<tf.Tensor: shape=(), dtype=float32, numpy=5.0>

$L_1$ norm, which is expressed as the sum of the absolute values of the vector elements

$$ ||x||_1 = \sum_{i=1}^n |x_i| $$


In [59]:
tf.reduce_sum(tf.abs(u))

<tf.Tensor: shape=(), dtype=float32, numpy=7.0>

In [60]:
tf.norm(tf.ones((4, 9)))

<tf.Tensor: shape=(), dtype=float32, numpy=6.0>

In [62]:
tf.ones((4, 9))

<tf.Tensor: shape=(4, 9), dtype=float32, numpy=
array([[1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1.]], dtype=float32)>

In [61]:
tf.norm(tf.ones((4, 9)))

<tf.Tensor: shape=(), dtype=float32, numpy=6.0>

In [63]:
A

<tf.Tensor: shape=(5, 4), dtype=float32, numpy=
array([[ 0.,  1.,  2.,  3.],
       [ 4.,  5.,  6.,  7.],
       [ 8.,  9., 10., 11.],
       [12., 13., 14., 15.],
       [16., 17., 18., 19.]], dtype=float32)>

In [64]:
tf.transpose(tf.transpose(A)) == A

<tf.Tensor: shape=(5, 4), dtype=bool, numpy=
array([[ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True]])>

In [70]:
B = tf.reshape(tf.range(20, dtype=tf.float32), (5,4))
B

<tf.Tensor: shape=(5, 4), dtype=float32, numpy=
array([[ 0.,  1.,  2.,  3.],
       [ 4.,  5.,  6.,  7.],
       [ 8.,  9., 10., 11.],
       [12., 13., 14., 15.],
       [16., 17., 18., 19.]], dtype=float32)>

In [73]:
A + B

<tf.Tensor: shape=(5, 4), dtype=float32, numpy=
array([[ 0.,  2.,  4.,  6.],
       [ 8., 10., 12., 14.],
       [16., 18., 20., 22.],
       [24., 26., 28., 30.],
       [32., 34., 36., 38.]], dtype=float32)>

In [74]:
tf.transpose(B) + tf.transpose(A) == tf.transpose(A + B)

<tf.Tensor: shape=(4, 5), dtype=bool, numpy=
array([[ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True]])>

In [75]:
q = tf.reshape(tf.range(9,dtype=tf.float32), (3,3))
q

<tf.Tensor: shape=(3, 3), dtype=float32, numpy=
array([[0., 1., 2.],
       [3., 4., 5.],
       [6., 7., 8.]], dtype=float32)>

In [76]:
q + tf.transpose(q)

<tf.Tensor: shape=(3, 3), dtype=float32, numpy=
array([[ 0.,  4.,  8.],
       [ 4.,  8., 12.],
       [ 8., 12., 16.]], dtype=float32)>

In [77]:
X = tf.reshape(tf.range(27, dtype=tf.float32), (3,3,3))
X

<tf.Tensor: shape=(3, 3, 3), dtype=float32, numpy=
array([[[ 0.,  1.,  2.],
        [ 3.,  4.,  5.],
        [ 6.,  7.,  8.]],

       [[ 9., 10., 11.],
        [12., 13., 14.],
        [15., 16., 17.]],

       [[18., 19., 20.],
        [21., 22., 23.],
        [24., 25., 26.]]], dtype=float32)>

In [78]:
len(X)

3